# 5 Functions I Have Learn from Python's Numpy, You Might Wanna Know


NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays ([Wikipedia-Numpy](https://en.wikipedia.org/wiki/NumPy)).
These are some list I've learn from Numpy function.

- Function 1 `np.average`
- Function 2 `np.char.count`
- Function 3 `np.transpose`
- Function 4 `np.where`
- Function 5 `np.sum`

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [3]:
import numpy as np

In [4]:
# List of functions explained 
function1 = np.average
function2 = np.char.count
function3 = np.transpose
function4 = np.where
function5 = np.sum

## Function 1 - np.average

`np.average` is to count the averaged of Numpy's array.

In [5]:
# Example 1 - working
a = np.array([[[1,2,3],
               [2,2,2]],
              [[3,2,1],
               [5,6,7]]])

print("List of the array a:")
print(a)
print("\nAverage of the array is:")
print(np.average(a))

List of the array a:
[[[1 2 3]
  [2 2 2]]

 [[3 2 1]
  [5 6 7]]]

Average of the array is:
3.0


Average of the array a above is all the sum of the index `(36)`, and then divide it by the count of the index `(12)`.

In [6]:
# Example 2 - working
a = np.array([[[1,2,3],
               [2,2,2]],
              [[3,2,1],
               [5,6,7]]])

print("List of the array a:")
print(a)
print("\nAverage of the array of axis 1 is:")
print(np.average(a, axis =1))

List of the array a:
[[[1 2 3]
  [2 2 2]]

 [[3 2 1]
  [5 6 7]]]

Average of the array of axis 1 is:
[[1.5 2.  2.5]
 [4.  4.  4. ]]


We also can access average of `axis 1` or `axis 0`. In Example 2 we try to find `vertical axis`'s average from the array.

In [7]:
# Example 3 - breaking
a = np.array([[[1,2,3],
               [2,2,2]],
              [[3,2,1],
               [5,6,7]]])

print("List of the array a:")
print(a)
print("\nAverage of the array in index (2) is:")
print(np.average(a[2]))

List of the array a:
[[[1 2 3]
  [2 2 2]]

 [[3 2 1]
  [5 6 7]]]

Average of the array in index (2) is:


IndexError: index 2 is out of bounds for axis 0 with size 2

In Example 3 there is an error because we try to find an average of not existing index from the array. So before access particular average of an array, you can check the shape of the array by typing `array_name.shape`.

With `np.average` function we can easily count the average value of simple and complex array.

In [8]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "umarhasan09/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/umarhasan09/numpy-array-operations


'https://jovian.ai/umarhasan09/numpy-array-operations'

## Function 2 - np.char.count

`np.char.count` to count specific char in array.

In [9]:
# Example 1 - working
a = np.array(['THis Is just', 'a simple', 'example', 'of an Array.'])

np.char.count(a, 'i')

array([1, 1, 0, 0])

You can count number of specific letter or word in a list of an array. Remember it is case sensitive.

In [10]:
# Example 2 - working
a = np.array(['THis Is just', 'a simple', 'example', 'of an Array.'])

np.char.count(a, ' ',start=0,end=7)
#count a space

array([1, 1, 0, 2])

You even can count specific character (in example we try to find space) from specific index position. 

In [11]:
# Example 3 - breaking
a = np.array(['THis Is just', 'a simple', 'example', 'of an Array.'])

np.char.count(a, ' ',start='T',end='t')

TypeError: slice indices must be integers or None or have an __index__ method

You cannot count specific character with start and end of a letter of the list from the array.

`np.char.count` make it easy to count number of character even in a long sentences.

In [12]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "umarhasan09/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/umarhasan09/numpy-array-operations


'https://jovian.ai/umarhasan09/numpy-array-operations'

## Function 3 - np.transpose

`np.transpose` use to transpose and also modify shape of an array.

In [13]:
# Example 1 - working
x = np.arange(8).reshape((2,4))

print('Actual array x:', np.arange(8))
print('Original array shape:', np.arange(8).shape)
print('\nAfter reshape to (2,4):\n', x)
print('Array shape after reshape:', x.shape)
print('\nAfter transpose:\n',np.transpose(x))
print('Array x shape after transpose:', np.transpose(x).shape)

Actual array x: [0 1 2 3 4 5 6 7]
Original array shape: (8,)

After reshape to (2,4):
 [[0 1 2 3]
 [4 5 6 7]]
Array shape after reshape: (2, 4)

After transpose:
 [[0 4]
 [1 5]
 [2 6]
 [3 7]]
Array x shape after transpose: (4, 2)


`np.transpose` make an array transposing shape and the value.

In [14]:
# Example 2 - working
x = np.zeros((1,3,2))
y = np.transpose(x, (1,0,2))

print("Actual array:\n", x)
print("Actual shape:",x.shape)
print("\nArray after transpose:\n",y)
print("Shape after transpose:",y.shape)

Actual array:
 [[[0. 0.]
  [0. 0.]
  [0. 0.]]]
Actual shape: (1, 3, 2)

Array after transpose:
 [[[0. 0.]]

 [[0. 0.]]

 [[0. 0.]]]
Shape after transpose: (3, 1, 2)


We also can transpose matrix `zeros` or `ones` (Read more:[Matrix Library](https://numpy.org/doc/stable/reference/routines.matlib.html)) to specific shape we want.

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
z = np.ones((2,3,4))
np.transpose(z,(4,2,3))

AxisError: axis 4 is out of bounds for array of dimension 3

As a note: the value after `z` in `np.transpose(z,(4,2,3))` is not actual value of the array, but the axes that we modify. So the correct transpose suppose to be `np.transpose(z,(2,0,1))`.

Now you can make a transpose array from existing array, and you did not need to make a new array.

In [16]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "umarhasan09/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/umarhasan09/numpy-array-operations


'https://jovian.ai/umarhasan09/numpy-array-operations'

## Function 4 - np.where

`np.where` use to search the specific condition. And we can return it to specific value that we want.

In [17]:
# Example 1 - working
x = np.arange(7)
print(x)
np.where(x<3, x, 2*x)

[0 1 2 3 4 5 6]


array([ 0,  1,  2,  6,  8, 10, 12])

`(x < 2, x` : If x smaller than 2, return x.

`, 2*x)`    : Else, return 2*x.

In [18]:
# Example 2 - working
x = np.array([True, False, False, False])
print(x)
y = np.array([1,2,3,4])
z = np.array([5,6,7,8])
np.where(x, y, z)

[ True False False False]


array([1, 6, 7, 8])

Every `x` array contain True value, it return to `y` array list. If not, it return to `z` array list.

In [19]:
# Example 3 - breaking
x = np.array([True, False, False, False])
print(x)
np.where(x, [1,2,3], [0,1,2,3])

[ True False False False]


ValueError: operands could not be broadcast together with shapes (4,) (3,) (4,) 

It breaks because the True statement (`[1,2,3]`) only three value. You need to make the same shape as the array list.

You can use `np.where` to find specific value from your dataset. More: [numpy.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html#numpy.where).

In [20]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "umarhasan09/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/umarhasan09/numpy-array-operations


'https://jovian.ai/umarhasan09/numpy-array-operations'

## Function 5 - np.sum

`np.sum` use when you want to sum the value of array.

In [21]:
# Example 1 - working
x = np.array([[1,2,3],
              [-2,1,3],
              [3,2,-1],
              [2,3,2]])
print('The array:\n',x,'\nWith shape:',x.shape)
print('\nThe sum of an array:\n',np.sum(x))
print('\nThe sum of an array axis=0:\n',np.sum(x,axis=0))
print('\nThe sum of an array axis=1:\n',np.sum(x,axis=1))

The array:
 [[ 1  2  3]
 [-2  1  3]
 [ 3  2 -1]
 [ 2  3  2]] 
With shape: (4, 3)

The sum of an array:
 19

The sum of an array axis=0:
 [4 8 7]

The sum of an array axis=1:
 [6 2 4 7]


When you sum `axis = 0`, it means you sum the value of every index n in every list from an array (across the column). When you sum `axis = 1`, it means you sum all the value of each list from the array (across the row).

In [22]:
# Example 2 - working
print('The array:\n',x,'\nWith shape:',x.shape)
print('\nThe sum of an array axis=0:\n',np.sum(x,axis=0,keepdims=True,initial=5))
print('\nThe sum of an array axis=1:\n',np.sum(x,axis=1,keepdims=True,initial=5))

The array:
 [[ 1  2  3]
 [-2  1  3]
 [ 3  2 -1]
 [ 2  3  2]] 
With shape: (4, 3)

The sum of an array axis=0:
 [[ 9 13 12]]

The sum of an array axis=1:
 [[11]
 [ 7]
 [ 9]
 [12]]


You can keep the actual dimension of the array by giving keyword `keepdims=True`. And you also can add the sum with specific value by giving keyword `intial=n`.

In [23]:
# Example 3 - breaking
x = np.array([[1,2,'True'],
              [-2,False,3],
              [3,2,-1],
              [2,3,True]])
np.sum(x)

TypeError: cannot perform reduce with flexible type

You cannot sum a string from this function. So be careful when you writing a **True** or **False** value. 

It is one of the powerful function from Numpy library you can use when you work with your data.

In [24]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "umarhasan09/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/umarhasan09/numpy-array-operations


'https://jovian.ai/umarhasan09/numpy-array-operations'

## Conclusion

In this Notebook you learn 5 functions of Numpy library about how the function work, and when the function did not work (error). You can experiment more with this 5 functions by adding some cell below the function.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Numpy Average : https://numpy.org/doc/stable/reference/generated/numpy.average.html
* Numpy Character Count : https://numpy.org/doc/stable/reference/generated/numpy.char.count.html
* Numpy Transpose : https://numpy.org/doc/stable/reference/generated/numpy.transpose.html
* Numpy Sum : https://numpy.org/doc/stable/reference/generated/numpy.sum.html#numpy.sum

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>